# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "avada"
client_id = "2a2177a38fd3d85646897dbb46ca72f1"
application_url = "https://adware-decline-switch-muscles.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://adware-decline-switch-muscles.trycloudflare.com/auth/shopify/callback",
  "https://adware-decline-switch-muscles.trycloudflare.com/authSa/shopify/callback",
  "https://adware-decline-switch-muscles.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "avada-training-app.myshopify.com"
